export enum ACTIONS {
  DELETE = "Deleted",
  CREATE = "Created",
  ARCHIVE = "Archived",
  RESTORE = "Restored",
  UPDATE = "Updated",
  BLOCK = "Blocked",
  ACTIVATE = "Activated",
  UPDATEPROFILE = "Profile Updated",
  UPDATEDOCUMENT = "Document Updated",
  STARTED = "Started",
  CANCELLED = "Cancelled",
  COMPLETED = "Completed",
  Approved = "Approved",
  Rejected = "Rejected",
  PAID = "Paid",
  ADDEDDOCUMENT = "Added Document",
  DELETEDDOCUMENT = "Deleted Document",
  PAYFOR = "Pay For",
}
export enum MODELS {
  USER = "User",
  NOTIFICATION = "Notification",
  ACCOUNT = "Account",
  CONFIGURATION = "Configuration",
  DOCUMENTCATEGORY = "DocumentCategory",
  DOCUMENT = "Document",
  PROPERTY = "Property",
  UNIT = "Unit",
  TENANT = "Tenant",
  OWNER = "Owner",
  LEASE = "Lease",
  RENTINCREASE = "RentIncrease",
  PAYMENT = "Payment",
  PAYMENTPLAN = "PaymentPlan",
  REQUEST = "Request",
  SALES = "Sales",
}
